/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class CntPendingQueryResponse implements Serializable {

    @JsonProperty("cntPendingReqs")
    @ColumnAlias("cntPendingReqs")
    private Long cntPendingReqs;

    public Long getCntPendingReqs() {
        return this.cntPendingReqs;
    }

    public void setCntPendingReqs(Long cntPendingReqs) {
        this.cntPendingReqs = cntPendingReqs;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CntPendingQueryResponse)) return false;
        final CntPendingQueryResponse cntPendingQueryResponse = (CntPendingQueryResponse) o;
        return Objects.equals(getCntPendingReqs(), cntPendingQueryResponse.getCntPendingReqs());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCntPendingReqs());
    }
}
