/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class PendingVacationRequestsResponse implements Serializable {

    @JsonProperty("id")
    @ColumnAlias("id")
    private Integer id;
    @JsonProperty("lname")
    @ColumnAlias("lname")
    private String lname;
    @JsonProperty("startdate")
    @ColumnAlias("startdate")
    private Date startdate;
    @JsonProperty("status")
    @ColumnAlias("status")
    private Character status;
    @JsonProperty("enddate")
    @ColumnAlias("enddate")
    private Date enddate;
    @JsonProperty("eid")
    @ColumnAlias("eid")
    private Integer eid;
    @JsonProperty("fname")
    @ColumnAlias("fname")
    private String fname;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getLname() {
        return this.lname;
    }

    public void setLname(String lname) {
        this.lname = lname;
    }

    public Date getStartdate() {
        return this.startdate;
    }

    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    public Character getStatus() {
        return this.status;
    }

    public void setStatus(Character status) {
        this.status = status;
    }

    public Date getEnddate() {
        return this.enddate;
    }

    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    public Integer getEid() {
        return this.eid;
    }

    public void setEid(Integer eid) {
        this.eid = eid;
    }

    public String getFname() {
        return this.fname;
    }

    public void setFname(String fname) {
        this.fname = fname;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof PendingVacationRequestsResponse)) return false;
        final PendingVacationRequestsResponse pendingVacationRequestsResponse = (PendingVacationRequestsResponse) o;
        return Objects.equals(getId(), pendingVacationRequestsResponse.getId()) &&
                Objects.equals(getLname(), pendingVacationRequestsResponse.getLname()) &&
                Objects.equals(getStartdate(), pendingVacationRequestsResponse.getStartdate()) &&
                Objects.equals(getStatus(), pendingVacationRequestsResponse.getStatus()) &&
                Objects.equals(getEnddate(), pendingVacationRequestsResponse.getEnddate()) &&
                Objects.equals(getEid(), pendingVacationRequestsResponse.getEid()) &&
                Objects.equals(getFname(), pendingVacationRequestsResponse.getFname());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getLname(),
                getStartdate(),
                getStatus(),
                getEnddate(),
                getEid(),
                getFname());
    }
}
