/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

public class RejectLeaveRequest implements Serializable {

    @JsonProperty("id")
    private Integer id;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RejectLeaveRequest)) return false;
        final RejectLeaveRequest rejectLeaveRequest = (RejectLeaveRequest) o;
        return Objects.equals(getId(), rejectLeaveRequest.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}
